site_name: Documentation Logger
site_url: https://documentation-logger.readthedocs.io/
copyright: Laboratoire Ampère

plugins:
  - with-pdf:
      author: Axel Chabot
      cover_subtitle: Documentation matérielle et logicielle
      toc_title: Table des matières

theme:
  name: material
  language: fr
