site_name: Documentation Logger
copyright: Laboratoire Ampère

#plugins:
#  - with-pdf:
#      author: Axel Chabot
#      cover_subtitle: Documentation materielle et logicielle
#      toc_title: Table des matières

theme:
  name: material
  language: fr
