site_name: Documentation Logger
site_description: Documentation materielle et logicielle d'une carte d'acquisition autonome
copyright: Laboratoire Ampère
repo_url: https://github.com/axoulc/Documentation_Logger
site_url: https://doc-logger.netlify.app/
edit_uri: blob/main/docs/

theme:
  name: material
  language: fr

nav:
  - Accueil: index.md
  - Présentation Matérielle: hardware.md
  - Programmation: prog.md

plugins:
  - search
  - with-pdf:
      author: Axel Chabot
      cover_subtitle: Documentation materielle et logicielle
      toc_title: Table des matières
      output_path: pdf/documentation_logger.pdf

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
