site_name: Documentation Logger
site_description: Documentation materielle et logicielle d'une carte d'acquisition autonome
copyright: Laboratoire Ampère
site_dir: /site
repo_url: https://github.com/axoulc/Documentation_Logger

theme:
  name: material
  language: fr

pages:
  - 'Accueil': index.md
  - 'Matériel': hardware.md


#plugins:
#  - with-pdf:
#      author: Axel Chabot
#      cover_subtitle: Documentation materielle et logicielle
#      toc_title: Table des matières
